version: '3.7'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_2019
    environment:
      SA_PASSWORD: Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

